// ── Premium Product Images ────────────────────────────────────────────────────
// Replace these with actual Telangana Toddy photos in production.
// Currently using picsum.photos (curated Unsplash catalog) — unique, beautiful, reliable.
export const IMAGES = {
  freshToddy:   'https://picsum.photos/seed/kallu-morning-fresh/600/600',
  eveningToddy: 'https://picsum.photos/seed/kallu-evening-sap/600/600',
  iceApple:     'https://picsum.photos/seed/tati-munjalu-cool/600/600',
  palmFruit:    'https://picsum.photos/seed/tati-pandu-ripe/600/600',
  palmJaggery:  'https://images.unsplash.com/photo-1627485937980-221c88ac04e9?w=600&auto=format&fit=crop&q=80',
  palmSprouts:  'https://picsum.photos/seed/tati-ginja-sprout/600/600',
  palmLeaves:   'https://picsum.photos/seed/tataaku-craft-leaf/600/600',
  palmSugar:    'https://picsum.photos/seed/tati-pancha-sugar/600/600',
  palmTree:     'https://picsum.photos/seed/palmyra-borassus-sky/600/600',
  toddyTapper:  'https://picsum.photos/seed/geetha-tapper-climb/600/600',
  toddyPots:    'https://picsum.photos/seed/clay-kunda-toddy/600/600',
  village:      'https://picsum.photos/seed/andhra-rural-morning/600/600',
  palmForest:   'https://picsum.photos/seed/palmyra-forest-telangana/600/600',
  sunrise:      'https://picsum.photos/seed/sunrise-palm-grove-ap/600/600',
  toddyFoam:    'https://picsum.photos/seed/kallu-foam-white/600/600',
  woodenServing:'https://picsum.photos/seed/wooden-serve-rustic/600/600',
  ecoGlass:     'https://picsum.photos/seed/bamboo-eco-cup-drink/600/600',
  toddyTreeRow: 'https://picsum.photos/seed/palmyra-row-tall/600/600',
  claypot:      'https://picsum.photos/seed/clay-matka-vessel/600/600',
  palmLeavesDew:'https://picsum.photos/seed/dew-leaf-morning/600/600',
  palmTrunk:    'https://picsum.photos/seed/borassus-trunk-bark/600/600',
  jaggeryWood:  'https://images.unsplash.com/photo-1627485937980-221c88ac04e9?w=600&auto=format&fit=crop&q=80',
  heroDawn:     'https://picsum.photos/seed/hero-toddy-dawn-ap/800/500',
  heroGreen:    'https://picsum.photos/seed/hero-palm-green-grove/800/500',
  heroClaypot:  'https://picsum.photos/seed/hero-clay-toddy-pots/800/500',
};

// ── Products ─────────────────────────────────────────────────────────────────
export const PRODUCTS = [
  {
    id: '1',
    name: 'Fresh Morning Toddy',
    nameTelugi: 'తాజా పొద్దున కల్లు',
    category: 'toddy',
    price: 200,
    unit: 'bottle',
    unitSize: '2 Litres',
    image: IMAGES.freshToddy,
    images: [IMAGES.freshToddy, IMAGES.toddyFoam, IMAGES.toddyPots, IMAGES.palmTree, IMAGES.woodenServing],
    description: 'Fresh morning toddy tapped at dawn from tall Palmyra palm trees by our skilled tappers. Natural, pure, and full of natural sugars. Best consumed within 4 hours of tapping.',
    benefits: ['Rich in natural probiotics', 'Contains Vitamin B complex', 'Natural energy booster', 'Aids digestion', 'Rich in potassium & minerals'],
    availability: true,
    stock: 50,
    rating: 4.8,
    reviews: 124,
    session: 'morning',
    cutoffTime: '10:00',
    isFeatured: true,
    tag: 'Best Seller',
  },
  {
    id: '2',
    name: 'Evening Toddy',
    nameTelugi: 'సాయంత్రం కల్లు',
    category: 'toddy',
    price: 180,
    unit: 'bottle',
    unitSize: '2 Litres',
    image: IMAGES.eveningToddy,
    images: [IMAGES.eveningToddy, IMAGES.claypot, IMAGES.toddyTreeRow, IMAGES.woodenServing, IMAGES.palmForest],
    description: 'Evening toddy with a rich, slightly fermented taste collected from mature palm trees during golden hour. Full-bodied and aromatic.',
    benefits: ['Helps with relaxation', 'Rich in carbohydrates', 'Contains natural yeast', 'Promotes restful sleep', 'Natural probiotics'],
    availability: true,
    stock: 40,
    rating: 4.6,
    reviews: 89,
    session: 'evening',
    cutoffTime: '18:00',
    isFeatured: true,
    tag: 'Popular',
  },
  {
    id: '3',
    name: 'Ice Apple (Tati Munjalu)',
    nameTelugi: 'తాటి ముంజలు',
    category: 'ice_apple',
    price: 50,
    unit: 'piece',
    unitSize: '1 piece',
    image: IMAGES.iceApple,
    images: [IMAGES.iceApple, IMAGES.palmFruit, IMAGES.ecoGlass, IMAGES.palmTree, IMAGES.woodenServing],
    description: 'Fresh ice apples — Tati Munjalu in Telugu. Cool, translucent, refreshing and perfect for summer. Nature\'s coolant, grown on tall Palmyra palms.',
    benefits: ['Natural body coolant', 'Prevents dehydration', 'Rich in dietary fiber', 'Low calorie', 'Natural electrolytes'],
    availability: true,
    stock: 100,
    rating: 4.9,
    reviews: 211,
    session: 'all',
    isFeatured: true,
    tag: 'Summer Special',
  },
  {
    id: '4',
    name: 'Palm Fruit (Tati Pandu)',
    nameTelugi: 'తాటి పండు',
    category: 'palm_fruit',
    price: 30,
    unit: 'piece',
    unitSize: '1 piece',
    image: IMAGES.palmFruit,
    images: [IMAGES.palmFruit, IMAGES.palmTree, IMAGES.toddyTreeRow, IMAGES.palmLeavesDew, IMAGES.woodenServing],
    description: 'Ripe palm fruit, sweet and nutritious. Harvested fresh from traditional Palmyra palm trees. A nutritional powerhouse.',
    benefits: ['Rich in antioxidants', 'High in natural sugars', 'Good for skin health', 'Rich in Vitamins A, B, C', 'Anti-inflammatory'],
    availability: true,
    stock: 80,
    rating: 4.5,
    reviews: 67,
    session: 'all',
    isFeatured: false,
  },
  {
    id: '5',
    name: 'Palm Jaggery (Tati Bellam)',
    nameTelugi: 'తాటి బెల్లం',
    category: 'palm_jaggery',
    price: 120,
    unit: 'pack',
    unitSize: '500g',
    image: IMAGES.palmJaggery,
    images: [IMAGES.palmJaggery, IMAGES.jaggeryWood, IMAGES.woodenServing, IMAGES.palmTree, IMAGES.palmSugar],
    description: 'Traditional palm jaggery made from fresh toddy sap. Zero chemicals, 100% natural. A healthy alternative to refined sugar with a distinctive caramel taste.',
    benefits: ['Iron-rich natural sweetener', 'Zero artificial chemicals', 'Boosts immunity', 'Good for digestion', 'Rich in calcium & minerals'],
    availability: true,
    stock: 60,
    rating: 4.7,
    reviews: 156,
    session: 'all',
    isFeatured: true,
    tag: 'Organic',
  },
  {
    id: '6',
    name: 'Palm Sprouts (Tati Ginja)',
    nameTelugi: 'తాటి గింజ',
    category: 'palm_sprouts',
    price: 40,
    unit: 'piece',
    unitSize: '1 piece',
    image: IMAGES.palmSprouts,
    images: [IMAGES.palmSprouts, IMAGES.palmTree, IMAGES.toddyTreeRow, IMAGES.palmLeavesDew],
    description: 'Tender palm sprouts — a rare delicacy. Sweet and crunchy, perfect as a healthy snack or in salads.',
    benefits: ['High dietary fiber', 'Natural cooling properties', 'Rich in calcium', 'Low glycemic index', 'Protein-rich'],
    availability: true,
    stock: 30,
    rating: 4.4,
    reviews: 43,
    session: 'all',
    isFeatured: false,
  },
  {
    id: '7',
    name: 'Palm Leaves Products',
    nameTelugi: 'తాటాకు ఉత్పత్తులు',
    category: 'palm_leaves',
    price: 150,
    unit: 'set',
    unitSize: 'Set of 10',
    image: IMAGES.palmLeaves,
    images: [IMAGES.palmLeaves, IMAGES.palmLeavesDew, IMAGES.palmTrunk, IMAGES.palmTree, IMAGES.woodenServing],
    description: 'Handcrafted eco-friendly products made from dried Palmyra leaves. Includes leaf plates, baskets, and traditional items. 100% biodegradable.',
    benefits: ['100% biodegradable', 'Eco-friendly alternative', 'Traditionally handcrafted', 'Supports local artisans', 'Natural material'],
    availability: true,
    stock: 25,
    rating: 4.6,
    reviews: 78,
    session: 'all',
    isFeatured: false,
  },
  {
    id: '8',
    name: 'Palm Sugar (Tati Pancha Dara)',
    nameTelugi: 'తాటి పంచదార',
    category: 'palm_jaggery',
    price: 90,
    unit: 'pack',
    unitSize: '250g',
    image: IMAGES.palmSugar,
    images: [IMAGES.palmSugar, IMAGES.jaggeryWood, IMAGES.woodenServing, IMAGES.palmTree, IMAGES.palmJaggery],
    description: 'Fine crystalline palm sugar made from evaporated toddy sap. Lower glycemic index than cane sugar. Perfect for diabetics and health-conscious consumers.',
    benefits: ['Low glycemic index (35)', 'Rich in B vitamins', 'Contains potassium & magnesium', 'Healthier sugar alternative', 'Natural caramel flavor'],
    availability: true,
    stock: 45,
    rating: 4.5,
    reviews: 52,
    session: 'all',
    isFeatured: false,
  },
];

// ── Categories ───────────────────────────────────────────────────────────────
export const CATEGORIES = [
  { id: 'all', name: 'All', icon: 'apps-outline' },
  { id: 'toddy', name: 'Toddy', icon: 'wine-outline' },
  { id: 'ice_apple', name: 'Ice Apple', icon: 'snow-outline' },
  { id: 'palm_fruit', name: 'Palm Fruit', icon: 'nutrition-outline' },
  { id: 'palm_jaggery', name: 'Jaggery', icon: 'cube-outline' },
  { id: 'palm_sprouts', name: 'Sprouts', icon: 'flower-outline' },
  { id: 'palm_leaves', name: 'Leaves', icon: 'leaf-outline' },
];

// ── Order Statuses ────────────────────────────────────────────────────────────
export const ORDER_STATUSES = [
  { key: 'placed', label: 'Order Placed', telugi: 'ఆర్డర్ పెట్టబడింది', icon: 'receipt-outline', color: '#64b5f6' },
  { key: 'accepted', label: 'Accepted', telugi: 'ఆమోదించబడింది', icon: 'checkmark-circle-outline', color: '#81c784' },
  { key: 'preparing', label: 'Preparing', telugi: 'సిద్ధం చేస్తున్నారు', icon: 'time-outline', color: '#ffb74d' },
  { key: 'ready', label: 'Ready', telugi: 'సిద్ధంగా ఉంది', icon: 'bag-check-outline', color: '#4db6ac' },
  { key: 'out_for_delivery', label: 'Out For Delivery', telugi: 'డెలివరీకి వెళ్ళింది', icon: 'bicycle-outline', color: '#7986cb' },
  { key: 'delivered', label: 'Delivered', telugi: 'డెలివరీ అయింది', icon: 'home-outline', color: '#4caf50' },
  { key: 'cancelled', label: 'Cancelled', telugi: 'రద్దు చేయబడింది', icon: 'close-circle-outline', color: '#ef5350' },
];

// ── Educational Content ───────────────────────────────────────────────────────
export const EDUCATIONAL_CONTENT = [
  {
    id: 'edu1',
    title: 'What is Toddy (Kallu)?',
    titleTelugi: 'కల్లు అంటే ఏమిటి?',
    content: 'Toddy (కల్లు) is the natural sap extracted from Palmyra palm (Borassus flabellifer) flower stalks. It is a sweet, milky-white liquid when fresh and non-alcoholic. As it ferments, it becomes slightly alcoholic within a few hours. It has been part of Andhra Pradesh culture for thousands of years, mentioned even in ancient Telugu literature.',
    icon: 'wine-outline',
    color: '#4caf7d',
    image: IMAGES.freshToddy,
  },
  {
    id: 'edu2',
    title: 'Morning Toddy vs Evening Toddy',
    titleTelugi: 'పొద్దున కల్లు vs సాయంత్రం కల్లు',
    content: 'Morning toddy is collected at dawn and is sweet, fresh and mildly fizzy. It contains natural sugars and is similar to coconut water in taste. Evening toddy is collected after fermentation starts — it has a stronger, tangy, slightly alcoholic flavor. Both are prized for their unique taste profiles.',
    icon: 'sunny-outline',
    color: '#ffb74d',
    image: IMAGES.eveningToddy,
  },
  {
    id: 'edu3',
    title: 'Toddy Tapping Process',
    titleTelugi: 'కల్లు తీయు విధానం',
    content: 'A skilled toddy tapper (Kallu Geetha Karmikudu) climbs palm trees using a rope loop. He makes precise, shallow cuts on the flower stalk and ties a clay pot (చేతి కుండ) beneath the cut to collect the sap. Each palm yields 1-3 litres per tapping. The process is done at dawn and before sunset daily.',
    icon: 'construct-outline',
    color: '#ce93d8',
    image: IMAGES.toddyTapper,
  },
  {
    id: 'edu4',
    title: 'Palm Tree (Tati Chettu)',
    titleTelugi: 'తాటి చెట్టు',
    content: 'The Palmyra palm (Borassus flabellifer) is the state tree of Andhra Pradesh. It can live 100+ years and grow up to 30 meters tall. Every part is useful: leaves for crafts & writing, fruit for food, sap for toddy, seeds for sprouts, fiber for rope. It is drought-resistant and thrives in coastal Andhra Pradesh.',
    icon: 'leaf-outline',
    color: '#81c784',
    image: IMAGES.palmTree,
  },
  {
    id: 'edu5',
    title: 'Palm Fruit & Ice Apple',
    titleTelugi: 'తాటి పండు & ముంజలు',
    content: 'The Palmyra palm produces large fruits containing 1-3 seeds. Young seeds contain a clear, jelly-like flesh called "Ice Apple" (Tati Munjalu in Telugu). They are refreshing, cooling and sold in summer. Ripe seeds turn starchy and fibrous. The fruit outer shell is used for lamp oil and fuel.',
    icon: 'nutrition-outline',
    color: '#64b5f6',
    image: IMAGES.iceApple,
  },
  {
    id: 'edu6',
    title: 'Palm Jaggery & Sugar',
    titleTelugi: 'తాటి బెల్లం & పంచదార',
    content: 'Palm jaggery is made by boiling fresh toddy until it solidifies. It is dark brown with a distinct caramel flavor. Unlike cane jaggery, it is rich in iron, calcium and B vitamins. Palm sugar is further refined into crystalline form. Both have a lower glycemic index than refined sugar, making them healthier sweeteners.',
    icon: 'cube-outline',
    color: '#f4c842',
    image: IMAGES.palmJaggery,
  },
  {
    id: 'edu7',
    title: 'Health Benefits of Toddy',
    titleTelugi: 'కల్లు ఆరోగ్య ప్రయోజనాలు',
    content: 'Fresh (unfermented) toddy is nutritionally rich: high in Vitamin C, B-complex vitamins, natural sugars, and minerals. It contains riboflavin, thiamine, and iron. It is probiotic (beneficial bacteria from fermentation) and aids digestion. Traditional medicine uses it as a liver tonic. NOTE: Fermented toddy contains alcohol — consume responsibly.',
    icon: 'heart-outline',
    color: '#ef9a9a',
    image: IMAGES.palmFruit,
  },
  {
    id: 'edu8',
    title: 'Palm Leaves & Handicrafts',
    titleTelugi: 'తాటి ఆకులు & హస్తకళలు',
    content: 'Dried Palmyra palm leaves have been used for millennia. Ancient Telugu literature and scriptures were written on palm leaves (తాళపత్ర గ్రంథాలు). Today, artisans weave leaf plates, baskets, fans, hats, and decorative items. These eco-friendly products are biodegradable alternatives to plastic. Supporting them preserves traditional craftsmanship.',
    icon: 'flower-outline',
    color: '#a5d6a7',
    image: IMAGES.palmLeaves,
  },
  {
    id: 'edu9',
    title: 'Geetha Karmikula Community',
    titleTelugi: 'గీత కర్మికుల కుటుంబాలు',
    content: 'The Geetha Karmikula (also spelled Geeta Karmikula) community in Andhra Pradesh are the traditional toddy tappers. They have practiced this art for generations. Many families still depend on toddy tapping as their primary livelihood. ToddyConnect was built to directly support these families by connecting them with customers digitally.',
    icon: 'people-outline',
    color: '#90caf9',
    image: IMAGES.toddyTapper,
  },
  {
    id: 'edu10',
    title: 'Uses of Palm Products',
    titleTelugi: 'తాటి ఉత్పత్తుల ఉపయోగాలు',
    content: 'Palm products have diverse uses: Sap → toddy, jaggery, sugar, vinegar, yeast. Fruit → food, oil, fuel. Leaves → writing material, crafts, roofing. Timber → construction. Roots → medicinal use. Inflorescence → sweets (called Pathu/Panakam). The entire tree is a sustainable resource requiring no pesticides or fertilizers.',
    icon: 'grid-outline',
    color: '#ce93d8',
    image: IMAGES.palmForest,
  },
];

// ── Gallery Items ─────────────────────────────────────────────────────────────
export const GALLERY_ITEMS = [
  { id: 'g1', title: 'Palm Trees at Sunrise', category: 'trees', image: IMAGES.sunrise, desc: 'Beautiful Palmyra palms at golden hour in coastal Andhra Pradesh' },
  { id: 'g2', title: 'Toddy Tapper at Work', category: 'tappers', image: IMAGES.toddyTapper, desc: 'A skilled Geetha Karmikudu climbing to collect sap' },
  { id: 'g3', title: 'Traditional Clay Pots', category: 'pots', image: IMAGES.toddyPots, desc: 'Clay pots used for collecting and storing fresh toddy' },
  { id: 'g4', title: 'Ice Apple (Tati Munjalu)', category: 'fruit', image: IMAGES.iceApple, desc: 'Fresh translucent ice apples — nature\'s coolant' },
  { id: 'g5', title: 'Palm Jaggery Blocks', category: 'products', image: IMAGES.palmJaggery, desc: 'Freshly made organic palm jaggery blocks' },
  { id: 'g6', title: 'Village Morning', category: 'village', image: IMAGES.village, desc: 'A serene morning in a traditional palm-tree village' },
  { id: 'g7', title: 'Palm Forest', category: 'trees', image: IMAGES.palmForest, desc: 'Dense Palmyra palm forest in Andhra Pradesh' },
  { id: 'g8', title: 'Palm Leaves Craft', category: 'craft', image: IMAGES.palmLeaves, desc: 'Traditional handicrafts woven from dried palm leaves' },
];

// ── Educational Videos ────────────────────────────────────────────────────────
export const EDU_VIDEOS = [
  { id: 'v1', title: 'Toddy Tapping Process', desc: 'Watch a traditional Geetha Karmikudu tap a palm tree', thumb: IMAGES.toddyTapper, url: 'https://www.youtube.com/watch?v=example1' },
  { id: 'v2', title: 'Palm Jaggery Making', desc: 'How palm toddy is converted into jaggery', thumb: IMAGES.palmJaggery, url: 'https://www.youtube.com/watch?v=example2' },
  { id: 'v3', title: 'Ice Apple Season', desc: 'Harvesting and selling ice apples in summer', thumb: IMAGES.iceApple, url: 'https://www.youtube.com/watch?v=example3' },
];

// ── Government Updates ────────────────────────────────────────────────────────
export const GOVERNMENT_UPDATES = [
  {
    id: 'gov1',
    category: 'scheme',
    title: 'Toddy Tappers Welfare Scheme 2024',
    titleTelugi: 'కల్లు కార్మికుల సంక్షేమ పథకం 2024',
    content: 'The Andhra Pradesh government provides ₹2,000 per month as welfare assistance to registered toddy tappers under the Geetha Karmikula Sangham. Eligible tappers must register with the local Excise Department.',
    icon: 'cash-outline',
    color: '#81c784',
    date: '2024-01-15',
    source: 'AP Excise Department',
    urgent: false,
  },
  {
    id: 'gov2',
    category: 'insurance',
    title: 'Group Insurance Scheme for Tappers',
    titleTelugi: 'కల్లు కార్మికులకు సమూహ బీమా',
    content: 'Under the AP government\'s group insurance scheme, registered toddy tappers get life insurance of ₹2 lakh and accidental insurance of ₹4 lakh. Premium is ₹100/year, fully subsidized by the government for BPL families.',
    icon: 'shield-checkmark-outline',
    color: '#64b5f6',
    date: '2024-02-01',
    source: 'AP Labour Department',
    urgent: false,
  },
  {
    id: 'gov3',
    category: 'excise',
    title: 'Excise Department Notification: License Renewal',
    titleTelugi: 'ఎక్సైజ్ లైసెన్స్ పునరుద్ధరణ',
    content: 'Toddy shop licenses and tapper permits must be renewed before March 31, 2025. Apply at your nearest Excise Department office with Form-7A. Late renewal attracts ₹500 fine. Bring Aadhaar card and previous year\'s license.',
    icon: 'document-text-outline',
    color: '#ffb74d',
    date: '2024-12-01',
    source: 'AP State Excise Department',
    urgent: true,
  },
  {
    id: 'gov4',
    category: 'subsidy',
    title: 'Subsidy on Toddy Tapping Equipment',
    titleTelugi: 'కల్లు తీయు పరికరాలపై సబ్సిడీ',
    content: 'AP government provides 50% subsidy on purchase of safety equipment for toddy tappers: safety belts, helmets, climbing ropes and clay pots. Apply through Geetha Karmikula Sangham with income certificate.',
    icon: 'pricetag-outline',
    color: '#ce93d8',
    date: '2024-03-10',
    source: 'AP SC/ST Welfare Department',
    urgent: false,
  },
  {
    id: 'gov5',
    category: 'loan',
    title: 'Mudra Loan for Toddy Businesses',
    titleTelugi: 'తాటి వ్యాపారానికి ముద్ర రుణం',
    content: 'Toddy tappers can avail Mudra loans up to ₹10 lakh under Tarun category for expanding their palm product business. Collateral-free loans with 7% interest rate. Apply at any nationalized bank with Aadhaar and business plan.',
    icon: 'business-outline',
    color: '#4db6ac',
    date: '2024-04-05',
    source: 'MUDRA, GoI',
    urgent: false,
  },
  {
    id: 'gov6',
    category: 'welfare',
    title: 'Free Education for Tappers\' Children',
    titleTelugi: 'కార్మికుల పిల్లలకు ఉచిత విద్య',
    content: 'Children of registered Geetha Karmikula families are eligible for free education under the SC/BC scholarship scheme. Covers tuition, books and hostel facilities from Class 1 to Post-Graduation. Apply at nearest DEO office.',
    icon: 'school-outline',
    color: '#ef9a9a',
    date: '2024-06-01',
    source: 'AP Social Welfare Department',
    urgent: false,
  },
  {
    id: 'gov7',
    category: 'excise',
    title: 'New Toddy Pricing Policy 2024-25',
    titleTelugi: 'కొత్త కల్లు ధర విధానం 2024-25',
    content: 'The AP Excise Department has revised the maximum retail price (MRP) for toddy: Morning toddy ₹120/litre, Evening toddy ₹100/litre. Selling above MRP is a punishable offense under AP Excise Act Section 32.',
    icon: 'stats-chart-outline',
    color: '#90caf9',
    date: '2024-07-01',
    source: 'AP State Excise Department',
    urgent: false,
  },
];

// ── Shop / Delivery Config ────────────────────────────────────────────────────
export const SHOP_INFO = {
  name: 'Toddy Connect Main Shop',
  address: 'Benz Circle, Vijayawada, Andhra Pradesh 520010',
  phone: '+91 99999 99999',
  latitude: 16.5062,
  longitude: 80.648,
  openTime: '05:30 AM',
  closeTime: '08:00 PM',
  mapsLink: 'https://maps.google.com/?q=16.5062,80.648',
};

export const DELIVERY_CHARGES = [
  { maxKm: 1, charge: 20, label: 'Within 1 km' },
  { maxKm: 2, charge: 35, label: '1–2 km' },
];

export const MAX_DELIVERY_KM = 2;

// ── Admin Registry (Toddy Shops) ──────────────────────────────────────────────
// Each admin phone in ADMIN_REGISTRY must match the phones recognised as admin in AppContext.
export const ADMIN_REGISTRY = [
  {
    id: 'admin_001',
    phone: '9999999999',
    shopName: 'Kallu Reddy Toddy Shop',
    ownerName: 'Ravi Kumar Reddy',
    address: 'Benz Circle, Vijayawada, AP 520010',
    latitude: 16.5062,
    longitude: 80.648,
    rating: 4.8,
    totalRatings: 234,
    isOpen: true,
    openTime: '05:30 AM',
    closeTime: '08:00 PM',
    specialties: ['Fresh Morning Toddy', 'Evening Toddy', 'Ice Apple', 'Palm Fruit', 'Palm Jaggery'],
    description: 'Premium toddy directly from farms. Family-owned for 30+ years. Freshly tapped every morning and evening.',
    deliveryRadius: 2,
    minOrder: 100,
    image: 'https://picsum.photos/seed/toddy-shop-benz-circle/400/250',
  },
  {
    id: 'admin_002',
    phone: '0000000000',
    shopName: 'Naatu Kallu Depot',
    ownerName: 'Suresh Babu Yadav',
    address: 'Auto Nagar, Vijayawada, AP 520007',
    latitude: 16.5142,
    longitude: 80.656,
    rating: 4.5,
    totalRatings: 156,
    isOpen: true,
    openTime: '06:00 AM',
    closeTime: '07:30 PM',
    specialties: ['Fresh Toddy', 'Palm Jaggery', 'Palm Sugar', 'Palm Sprouts'],
    description: 'Authentic country toddy with rich taste. Serving customers for 20+ years. Home delivery available.',
    deliveryRadius: 1.5,
    minOrder: 80,
    image: 'https://picsum.photos/seed/naatu-kallu-depot-autonagar/400/250',
  },
];
